id: PB4A0F571
initial_creation_type: ocr
source_metadata:
  volumes:
    dd21e050d921435bb406b44aa31ab6c8:
      base_file: v052.txt
      image_group_id: I1PD95897
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་ཞེས་བྱ་བའི་འགྲེལ་པ།
      total_pages: 1426
      volume_number: 52
